### ISSUE TITLE
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ALAssetsLibrary saveImage:toAlbum:completion:failure:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by auriga-dev** [Kjuly/KYPhotoLibrary#31]
Hi there, I'm using XCode 6.3 and Swift 1.2 and when runing the code:
ALAssetsLibrary().saveImage(screenshot, toAlbum: "myAlbum", completion:nil, failure:nil)

I get the error:

> **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ALAssetsLibrary saveImage:toAlbum:completion:failure:]: unrecognized selector sent to instance

I use a bridging header to link the Objective C code with Swift

In the build phases I added the MobileCoreService and the AssetsLibrary framework

Any help would be much appreciated

**Comment by Kjuly** [comment]
Have u imported the .h file appropriately to ur Swift project?

**Comment by auriga-dev** [comment]
Yes I did with a briging

**Comment by auriga-dev** [comment]
Can you make a quick demo on Swift?

**Comment by Kjuly** [comment]
@auriga-dev sorry, i rarely use Swift for developing, it might take some time for doing this, and busy these days. I'm appreciate if someone else can help to do this, thx in advance :)
