### ISSUE TITLE
 not working iOS  11.3 , and 11.4    ?

### ISSUE THREAD

**Issue by ramanihiteshc** [Kjuly/KYPhotoLibrary#51]
if  latest iOS 11.3 and 11.4 then not working this one framework , how to solve  out this one problem. if iOS 11.0 below then working . save image and video custom folder then not create and not display photo library . how to solve out this one problem

**Comment by Kjuly** [comment]
Hi @Ramani1994 , the demo project works at my side (tried iOS 11.4.1), can u provide a sample project u used that can't make it work? You can host it in a temp repo, so i can download it & take a try.

Btw., plz make sure u've linked Photos.framework.
